apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-python-app-lmt
  labels:
    app: sample-python-app-lmt
spec:
 
    replicas: 3
    selector:
        matchLabels:
          app: sample-python-app-lmt
    template:
        metadata:
          labels:
              app: sample-python-app-lmt
 
        spec:
          containers:
            - name: sample-python-app-lmt
              image: 058264463902.dkr.ecr.us-east-1.amazonaws.com/ignite-eks-repo:${{ github.sha }}
              imagePullPolicy: Always
              ports:
                - containerPort: 5000
 
              env:
                - name: LOG_LEVEL
                  value: "INFO"
                - name: LOG_FILE
                  value: "/var/log/app.log"
                - name: MY_NODE_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: spec.nodeName
                - name: MY_POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: MY_POD_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: MY_POD_IP
                  valueFrom:
                    fieldRef:
                      fieldPath: status.podIP
                - name: MY_POD_SERVICE_ACCOUNT
                  valueFrom:
                    fieldRef:
                      fieldPath: spec.serviceAccountName
                - name: DB_USER_NAME
                  valueFrom:
                      configMapKeyRef:
                        name: dbconfig
                        key: DB_USER_NAME
                - name: DB_NAME
                  valueFrom:
                      configMapKeyRef:
                        name: dbconfig
                        key: DB_NAME
                - name: DB_PASSWORD
                  valueFrom:
                      secretKeyRef:
                        name: dbsecret
                        key: DB_PASSWORD
                - name: DB_HOST
                  valueFrom:
                      secretKeyRef:
                        name: dbsecret
                        key: DB_HOST                        
              volumeMounts:
                - name: log-volume
                  mountPath: /var/log
              resources:
                requests:
                  memory: "100Mi"
                  cpu: "50m"
                limits:
                  memory: "128Mi"
                  cpu: "100m"    
          volumes:
            - name: log-volume
              emptyDir: {}    
