apiVersion: v1
kind: Service
metadata:
  name: sample-python-app-lmt
spec:
 
    selector:
        app: sample-python-app-lmt
    ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
    type: NodePort
